site/content/demo/docs.md
site/content/demo/index.md
site/content/test/index.md
templates/default/components/MDX.js
templates/default/contentlayer.config.js
templates/default/layouts/docs.js
templates/default/layouts/unstyled.js
templates/default/tailwind.config.js
templates/default/tests/layouts.spec.js
templates/default/tests/pages.spec.js

Tasks from #8 
***
This PR adds support for pages to have different layouts if specified in frontmatter. There are two layouts `unstyled` and `docs`
- Two demo pages in markdown `content/demo`
- unstyled at [/demo](https://deploy-preview-15--spectacular-dragon-c1015c.netlify.app/demo)
- docs at [/demo/docs](https://deploy-preview-15--spectacular-dragon-c1015c.netlify.app/demo/docs)

[templates/default]: layouts for pages

---

site/content/config.js
templates/default/config/siteConfig.js

- moves `content/userConfig.js` to `config.js`
- hardcodes `/content` as a path to markdown notes in `siteConfg.js`
Closes #7

renamed "userConfig" & disabled content path setting via env 

---

site/content/docs/guides.md
site/content/docs/roadmap.md
site/content/docs/syntax.md

- syntax elements in the `docs/syntax` page split into three sections: CommonMark, GFM and Obsidian extensions (based on CommonMark and GFM specs, and Obsidian docs)
- a few more syntax elements added
- added "callouts" at the end of each section pointing to CommonMark and GFM specs, and Obsidian docs at the end of corresponding sections (for users to learn more about each syntax and so that we don't need to write down everything that's already there)

`docs/syntax` page adjustments

---

site/content/docs/math.md
templates/default/components/MDX.js
templates/default/contentlayer.config.js
templates/default/package-lock.json
templates/default/package.json
templates/default/styles/global.css

Resolves #64 
***
This PR adds support for using math syntax as in obsidian using the following remark and rehype plugins
- https://github.com/remarkjs/remark-math/tree/main/packages/remark-math
- https://github.com/remarkjs/remark-math/tree/main/packages/rehype-mathjax
Block math only transforms when `$$` signs are above and below the syntax. for eg.
```markdown
$$
\begin{vmatrix}a & b\\
c & d
\end{vmatrix}=ad-bc
$$
```

Math syntax support

---

site/content/docs/syntax.md
site/content/test/page-4.md
templates/default/package-lock.json
templates/default/package.json

This PR adds the feature to support transclusion links for images as used in Obsidian. It parses `![[Image.png]]` as an image element `<img src="assets/images/Image.png" className="internal" />`
Docs for this support is mentioned in [/docs/syntax](https://flowershow.app/docs/syntax)

Support transclusion links for images

---

site/content/docs/seo.md
templates/default/components/MDX.js
templates/default/contentlayer.config.js

Remaining task from #57 
***
This PR will add support to set per page images for social sharing preview.

[SEO]: Per page images for social share

---

site/content/config.js
templates/default/components/Layout.js
templates/default/pages/_all.js

Resolves #98 
***
Merging this PR will add a page at the route [/_all](https://deploy-preview-129--spectacular-dragon-c1015c.netlify.app/_all) which contains a sorted list of all other pages on the website.

[Pages]: All page listing

---

site/content/config.js
templates/default/components/Link.js
templates/default/components/MDX.js
templates/default/components/Nav.js
templates/default/tailwind.config.js

Tasks from #111 
***
This PR fixes the build error from next-seo images not present in config, adds support for next links and proper svg rendering, and adds optional rendering of the github icon if the url is present in config.

[#111]: Fixes to flowershow

---

site/content/docs/mdx.md
site/content/docs/seo.md
templates/default/.changeset/cold-pants-reply.md
templates/default/contentlayer.config.js
templates/default/package-lock.json
templates/default/package.json
templates/default/tests/markdownFeatures.spec.js

Resolves #60 
***
This PR adds:
*  Support for custom Obsidian style callouts to markdown blockquotes using the plugin from https://github.com/flowershow/remark-callouts
* replacements in docs that were using temporary callouts component.
- [docs/seo](https://deploy-preview-193--spectacular-dragon-c1015c.netlify.app/docs/seo#setting-global-meta-tags)
- [docs/mdx](https://deploy-preview-193--spectacular-dragon-c1015c.netlify.app/docs/mdx#what-is-mdx)
- docs/seo
- docs/mdx

[contentlayer,docs]: Add callouts plugin and update docs

---

packages/cli/lib/Installer.js
packages/cli/package-lock.json
packages/cli/package.json

Closes #228, #235
**Please don't merge.**
- change content/assets symlinks created by the CLI to include relative rather than absolute paths
- add console info about auto-creation of index.md and/or config.js files if they didn't exist in the user's content folder
- bump CLI version

CLI fixes after Alpha release

---

site/content/docs/callouts.md
site/content/docs/syntax.md
templates/default/.changeset/four-kids-travel.md
templates/default/package-lock.json
templates/default/package.json

***
Resolves #243 
This PR updates the callouts plugin and it's documentation.
***
* Bump remark-callouts `v1.0.1 --> v1.0.2` which contains fix for case insensitive match eg. `> [!TIP]`
* Move callouts docs from [docs/syntax](https://flowershow.app/docs/syntax) to [docs/callouts](https://deploy-preview-251--spectacular-dragon-c1015c.netlify.app/docs/callouts)
- Add documentation for supported types

Callouts fix and documentation

---

packages/template/lib/getPageData.js
site/content/docs/mdx.md
site/content/getters/todos.js

Closes #224
- small fix to `getPageData` lib function to support async getters (e.g. for external data fetching)
- add basic info about `data` frontmatter field
We should probably come back to this when we add support for defining custom document types with custom fields, which could then be used as metadata of imported files in getters for filtering and other manipulations (like we do for ecosystem plots). Or at least add a list of fields available on the documents by default (i.e. `sourceFilePath` etc.)

224 data field type

---

packages/cli/CHANGELOG.md
packages/cli/package.json
packages/cli/src/bin/cli.js
packages/cli/src/e2e/test.bats
packages/cli/src/lib/buildExport.js
site/content/docs/publish-tutorial.md

Closes #275 
- renamed `flowershow build-static` to `flowershow export`
- updated self-publish tutorial

Rename build-static to export

---

site/content/Pasted image 20221130120203.png
site/content/docs/blog-tutorial.md
site/content/docs/blog.md
site/content/docs/index.md

Closes #318 
- doc page in `docs/blog`
- tutorial in `docs/blog-tutoral`

Blog support docs page and tutorial

---

packages/cli/README.md
packages/template-e2e/README.md
packages/template/README.md
site/README.md
site/content/docs/contributors.md

Closes #149
- created `docs/contributors` page with all the developer docs
- new section at the top with an overview of the repo structure
- added available CLI commands to `packages/cli/README.md`
- removed old info on E2E tests from `packages/template`
- created `packages/template-e2e/README.md` file with short info on running template tests
- added info on symlinking that happens in postinstall script to `site/README.md`

Docs page for developers

---

packages/template/public/excalidraw
site/content/assets/images/docs-excalidraw-images-1.png
site/content/assets/images/docs-excalidraw-images-2.png
site/content/assets/images/docs-excalidraw-images-3.png
site/content/docs/excalidraw.md

Closes #10 
This PR symlinks the excalidraw folder in public and adds docs for configuring Excalidraw images in Obsidian.
- Symlink excalidraw folder in `packages/template` ie. `content/excalidraw -->  public/excalidraw`
- Add docs for exporting excalidraw png or svg in Obsidian and symlink the folder @ [docs/excalidraw](https://deploy-preview-349--spectacular-dragon-c1015c.netlify.app/docs/excalidraw)

Export and symlink Excalidraw images

---

packages/template/layouts/blog.jsx
packages/template/layouts/docs.jsx
packages/template/tailwind.config.js

Tasks from #351 
This PR adds tailwind's default fonts and a heading font for easy configuration and use in layouts or components.
* Overwrite `tailwind.config.js` with tailwind's default fonts
* Add a custom `font-headings` property for headings
* Use semantic heading fonts in layouts

Default fonts in tailwind

---

packages/cli/src/bin/cli.ts
packages/cli/src/lib/Installer.ts
packages/template/package.json
scripts/symlink-site.js

Fixes a minor typo and passes the `type` parameter to [`fs.symlinkSync`](https://nodejs.org/api/fs.html#fssymlinktarget-path-type-callback) (which is used only on Windows and ignored on others) to remove the need to run as admin.

Allow installing as non-admin on Windows

---

.changeset/loud-hairs-attend.md
packages/core/package.json
packages/core/src/config/default.js
packages/core/src/ui/Base/CustomLink.tsx
packages/core/src/ui/Tooltip/Tooltip.tsx
packages/core/src/ui/Tooltip/index.ts
packages/template-e2e/src/tests/tooltips.spec.js
packages/template/package.json
packages/template/pages/[[...slug]].jsx
packages/template/styles/global.css
packages/template/tailwind.config.cjs
pnpm-lock.yaml
site/content/docs/link-previews.md

Closes #36 
This PR adds the feature to show previews for internal pages on hovering over it's link. This feature can also be disabled by setting `showLinkPreviews` property to false in `config.js` (enabled by default)
* Add new packages:
* core: 
- `@floating-ui/react-dom`
- `@floating-ui/react-dom-interactions`
- `framer-motion`
* template: `@tailwindcss/line-clamp`
* Add new Tooltip Component in core
* Modify CustomLink component in core
* Modify props for `CustomLink in template/pages/[[...slug]].jsx`
* Add tooltip styles in `template/styles/global.css`
* Add tailwind plugin in `template/tailwind.config.cjs`
* pnpm-lock updated
* update documentation in [docs/link-previews](https://deploy-preview-382--spectacular-dragon-c1015c.netlify.app/docs/link-previews)

Link previews on hover

---

.changeset/silly-ways-exercise.md
packages/template-e2e/project.json
packages/template-e2e/src/fixtures/components/NextLinkButton.jsx
packages/template-e2e/src/fixtures/content/mdxFeatures.md
packages/template-e2e/src/support/testsetup.sh
packages/template-e2e/src/tests/mdxFeatures.spec.js
packages/template/pages/[[...slug]].jsx

Closes #319
This PR fixes a problem with importing components that import Next.js components like `Link`, in markdown pages.
The solution was proposed by the contentlayer team; see https://github.com/contentlayerdev/contentlayer/issues/288).
- tweaks code string passed to contentlayer's `useMdxComponent` hook, by adding a prefix that set's the value of `process` variable
- adds relevant test files

Using components (in MDX) that import from next package (e.g. next/link)

---

packages/core/src/ui/BlogLayout/BlogLayout.tsx
packages/core/src/ui/DocsLayout/Docs.tsx
packages/core/src/ui/Nav/Nav.tsx

closes #400 
Added some classes to layouts so headings and other tags uses tailwind config for colors
- Added text-primary classes to headings, links, strong tags etc. in `Bloglayout` and `Docs`
- fix default background color in Nav

fix-nav-background-and-text-color

---

site/components/Hero.jsx

This PR fixes overlapping of typed text for Hero's title.
* add whitespace styles for typed text.

Fix typed text overlap in Hero

---

.changeset/silver-buses-tap.md
.changeset/wicked-grapes-hug.md
packages/core/CHANGELOG.md
packages/core/package.json
packages/core/src/ui/Comments/Disqus.tsx
packages/core/src/ui/Comments/Giscus.tsx
packages/core/src/ui/Comments/Utterances.tsx
packages/core/src/ui/Comments/index.tsx
packages/core/src/ui/Layout/Layout.tsx
packages/core/src/ui/types.ts
packages/template/contentlayer.config.ts
packages/template/package.json
packages/template/pages/_app.tsx
pnpm-lock.yaml
site/content/assets/images/page_comments.png
site/content/blog/index.md
site/content/config.js
site/content/docs/index.md
site/content/docs/page-comments.md

Closes #163 
This PR adds the feature to enable comments on pages by setting them up in config and/or frontmatter.
* Create comments components in core for [giscus](https://giscus.app/), [utterances](https://utteranc.es/) and [disqus](https://disqus.com)
* Add [giscus react](https://github.com/giscus/giscus-component) and [disqus-react](https://github.com/disqus/disqus-react) packages in core 
* Add configs in frontmatter and config.js
* configured to set page comments through frontmatter, or specified folders in comments' config. If both are not set then defaults to show on all pages. Frontmatter value takes precedence.
* Add documentation @ [docs/page-comments](https://deploy-preview-406--spectacular-dragon-c1015c.netlify.app/docs/page-comments)

Page comments / discussions

---

packages/template/styles/global.css

closes #272 
- changed `math-inline` class in `template/styles/global.css`
Equations in sentences now displays:

Fix inline Latex display

---

.changeset/tender-ravens-fetch.md
packages/template/contentlayer.config.ts
packages/template/package.json
packages/template/pages/[[...slug]].tsx
pnpm-lock.yaml

Closes #297 
Merging this PR will add meta title and description from content's (first) `H1`  and `paragraph` respectively, only if they are not specified in the page's frontmatter and if page content exists.
* Add resolvers for title and description in computed fields - `contentlayer.config.ts`
* Add package - https://github.com/remarkjs/strip-markdown
* Handle repeating titles in `pages/[[...slug]].tsx`

Auto extract title and description from content

---

.changeset/new-doors-fetch.md
packages/template/contentlayer.config.ts
packages/template/pages/[[...slug]].tsx
site/content/docs/index.md
site/content/docs/link-previews.md
site/content/index.md

closes #455 
Link previews boolean added to frontmatter
- frontmatter value `showLinkPreview` will be used first if it exists instead of siteConfig value `showLinkPreviews`
- added change to docs at  `/docs/link-previews`
- changed our home page and docs index page to not display link previews

Link previews per page added

---

.changeset/khaki-toys-crash.md
packages/core/src/ui/Blog/BlogItem.tsx
packages/core/src/ui/BlogLayout/BlogLayout.tsx
packages/core/src/ui/types.ts
packages/template-e2e/src/fixtures/content/getters/blogs.js
packages/template/contentlayer.config.ts
site/content/blog/2022-11-21-updated-features.md
site/content/blog/2022-11-30-wordpress-migration.md
site/content/blog/2022-12-08-updated-features.md
site/content/blog/2023-01-25-updated-features.md
site/content/blog/2023-02-16-nextjs-tutorial.md
site/content/blog/2023-02-17-updated-features.md
site/content/blog/alpha-release.md
site/content/blog/flowershow-setup-v0.0.1-for-alpha-users-june-2022.md
site/content/docs/blog-section-tutorial.md
site/content/docs/blog-tutorial.md
site/content/docs/blog.md
site/content/docs/comments.md
site/content/docs/custom-theme.md
site/content/docs/publish-tutorial.md
site/content/getters/blogs.js
site/content/notes/content-layer.md
site/content/notes/design-cloud-publishing.md
site/content/notes/digital-garden.md
site/content/notes/howto-signups-for-petitions-in-jamstack-world.md
site/content/notes/tutorial-flowershow-nextjs-template.md

closes #445 
- Uses `date` as default frontmatter field and uses `created` field if `date` is not found
- Blog layout components updated to use `date` instead of `created`
- `date` computed field added in `contentlayer.config`
- Since either `created` or `date` can be used, none of them is required, maybe there is a way to have at least one of them required?
- Tested that both date and created frontmatter fields works as expected

Make date the default field in frontmatter

---

package-lock.json

Hey @olayway 
I was trying to create a flowershow project and npm i was giving me the following error:
```bash
npm ERR! code ENOENT
npm ERR! syscall open
npm ERR! path /home/deme/Projects/datopian/flowershow-test/portaljs/packages/core/portaljs-core-1.0.7.tgz
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, open '/home/deme/Projects/datopian/flowershow-test/portaljs/packages/core/portaljs-core-1.0.7.tgz'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 
```
Seems like @portaljs/core was resolving to a local package.
This PR just regenerates `package-lock.json` and fixes it.

Fix flowershow install failing

---

lib/markdown.ts

- Fixes [Issue #519](https://github.com/datopian/flowershow/issues/519)
- Fixes [Issue #527](https://github.com/datopian/flowershow/issues/527)
This pull request addresses two specific issues and introduces a valuable enhancement to the Flowershow project. It enables users to add custom functionality before processing files, thus making it more versatile and accommodating for custom plugins or other enhancements.
1. **Custom Pre-Processing Functionality**
Introduced a pre-processing function, `preProcess`, which allows users to customize the content before further processing. Here is an example of this function:
```javascript
export default function preProcess(content) {
// Replace all occurrences of "=>" with "⟹"
return content.replace(/=>/g, '⟹');
}
This enables users to define their …
```

[][xs]: Add the ability to pass a preProcess function

---

package-lock.json
package.json

For https://github.com/datopian/flowershow/issues/587
- It watches for file changes in the `content` folder.
- Using `next-remote-watch`

[][m]: Implement hot-reloading

---

.gitignore
config/siteConfig.ts
content/config.mjs
pages/_app.tsx
public/sitemap.xml

Adds a type for the user config which makes it easier to know what's possible when setting up your own Flowershow instance.
Closes #625

Add user config type

---

README.md

updated the quickstart link to point to the current guide as opposed to the deprecated guide

Update README.md (outdated link)
