datopian/flowershow

site/content/index.md
site/content/subscribed.md

- a simple subscription form in the hero section
- subscription success page

Front page subscription form

---

site/content/index.md

Section with currently supported and under development features

---

templates/default/components/Layout.js

[Footer][xs]: Footer styling

---

templates/default/.eslintrc.json
templates/default/.prettierrc
templates/default/components/Layout.js
templates/default/components/Link.js
templates/default/components/MDX.js
templates/default/components/MobileNavigation.js
templates/default/components/Nav.js
templates/default/components/Pre.js
templates/default/components/Search.js
templates/default/components/ThemeSelector.js
templates/default/config/siteConfig.js
templates/default/contentlayer.config.js
templates/default/layouts/blog.js
templates/default/layouts/docs.js
templates/default/layouts/unstyled.js
templates/default/lib/gtag.js
templates/default/next.config.mjs
templates/default/package-lock.json
templates/default/package.json
templates/default/pages/[[...slug]].js
templates/default/pages/_all.js
templates/default/pages/_app.js
templates/default/playwright.config.js
templates/default/postcss.config.js
templates/default/tailwind.config.js
templates/default/tests/example.spec.js
templates/default/tests/markdown-page.js
templates/default/tests/pages.spec.js
templates/default/tests/wikilinks.spec.js

Following standard lint file and using prettierrc for formatting.

Add eslint and prettier

---

templates/default/contentlayer.config.js
templates/default/package-lock.json
templates/default/package.json

-- becomes ndash
--- becomes mdash
... becomes ellipse (even if there are spaces in between)
\n --- \n still creates a hr

remark-smartypants added

---

site/content/docs/config.md
templates/default/.changeset/seven-hounds-pay.md
templates/default/config/siteConfig.js
templates/default/contentlayer.config.js
templates/default/pages/[[...slug]].jsx

keep files unpublished config option

---

packages/cli/e2e/scripts/install.sh
packages/cli/e2e/test.bats
packages/cli/lib/Installer.js
packages/cli/lib/build.js
packages/cli/lib/buildStatic.js
packages/cli/lib/const.js
packages/cli/lib/install.js
packages/cli/lib/preview.js
site/content/assets/images/content_folder.png
site/content/assets/images/netlify_deploy.png
site/content/assets/images/npx_build.png
site/content/assets/images/npx_build_2.png
site/content/assets/images/npx_create.png
site/content/assets/images/npx_install.png
site/content/assets/images/npx_publish.png
site/content/docs/publish-tutorial.md
site/content/index.md
templates/default/package.json

- `build-static` command added
- ability to select assets folder from the list of available subfolders
- ability to choose not to use assets folder
- E2E adjustments
- enhanced frontpage self-publish and publish sections
- enhanced self-publish tutorial

Self publish updates

---

packages/template-e2e/src/fixtures/content/blog/blogtest1.md
packages/template-e2e/src/fixtures/content/blog/blogtest2.md
packages/template-e2e/src/fixtures/content/blog/index.md
packages/template-e2e/src/fixtures/content/blogtest3.md
packages/template-e2e/src/fixtures/content/getters/blogs.js
packages/template-e2e/src/tests/blog.spec.js

- added e2e test for new blog section

Blog support E2E tests

---

packages/template/components/BlogItem.jsx
packages/template/components/BlogsList.jsx
site/content/getters/blogs.js

- adds `Show more` button to load the next 10 blog posts

Show more button for blog posts

---

packages/template/components/Avatar.jsx
packages/template/components/Layout.jsx
packages/template/components/MobileNavigation.jsx
packages/template/components/Nav.jsx
packages/template/layouts/docs.jsx
packages/template/tailwind.config.js
site/components/Hero.jsx
site/components/WhatIsFlowershow.jsx

Tasks from #351 
This PR adds named theme colors in tailwind's config for customizing background et al.
* Add named color options in `tailwind.config.js` - *primary, secondary and background*
* refactor components and layouts to use semantic colors

[tailwind][s]: named theme colors

---

site/content/docs/mdx.md

Fix the shrug emoticon

---

site/content/assets/images/blogafter.png
site/content/assets/images/blogbefore.png
site/content/blog/2022-11-30-wordpress-migration.md

Closes #356 
- made recommended changes to existing Wordpress to Markdown tutorial

Wp to Md tutorial update

---

site/content/assets/images/darkafter.png
site/content/assets/images/defaultdark.png
site/content/assets/images/defaultfont.png
site/content/assets/images/fontafter.png
site/content/assets/images/lightafter.png
site/content/docs/custom-theme.md
site/content/docs/index.md

Closes #292 
This PR adds a fonts and colors theming tutorial to docs.
* Add tutorial doc @ docs/custom-theme.md
* Add link to tutorial in /docs section

Theming tutorial

---

packages/template/package.json
pnpm-lock.yaml
site/components/Hero.jsx

Closes #307 
This PR adds a typed text animation for the Hero title
* Add typed.js package in template
* Change Hero title with typed animation text
* update pnpm lock file

Add typed animations in Hero section

---

.changeset/healthy-lobsters-give.md
packages/core/src/ui/Layout/Layout.tsx
packages/core/src/ui/Layout/Sidebar.tsx
packages/core/src/ui/Nav/Nav.tsx
packages/core/src/ui/Nav/NavMobile.tsx
packages/core/src/ui/SiteToc/SiteToc.tsx
packages/core/src/ui/SiteToc/index.ts
packages/template/pages/_app.tsx
site/content/assets/images/site-toc.png
site/content/assets/images/site-wide-toc.png
site/content/docs/site-wide-toc.md

Closes #408 
- grouping of ToC items by first level subfolders of content folder

Site-wide ToC v.2. - grouping items

---

.changeset/chilly-comics-pretend.md
packages/core/src/ui/Base/CustomLink.tsx
packages/core/src/ui/Base/TwitterEmbed.tsx
site/content/docs/social-previews.md

closes #67 
- Twitter URLs in markdown turn into twitter embeds
Preview:
- `TwitterEmbed` component in core added
- `Customlink` Component updated
- doc added at `docs/social-previews`
- Core changes in PR needs to be published for this to work
- Dark/Light theme to be added later when our Theme switch is working

67 twitter embed

---

site/content/assets/images/twitterembed.png
site/content/blog/2022-11-21-updated-features.md
site/content/blog/2022-12-08-updated-features.md
site/content/blog/2023-01-25-updated-features.md
site/content/blog/2023-02-17-updated-features.md

closes #412 
- Flowershow February News Update added to blog

Flowershow news february

---

site/content/assets/images/blogpost.png
site/content/assets/images/datahub.png
site/content/assets/images/datopian.png
site/content/assets/images/fshowblogindex.png
site/content/assets/images/lifeitself.png
site/content/blog/2023-02-16-nextjs-tutorial.md

closes #396 
- NextJS template blog tutorial added

NextJS template tutorial

---

.gitignore
.lintstagedrc.json
packages/markdowndb/.babelrc
packages/markdowndb/.eslintrc.json
packages/markdowndb/README.md
packages/markdowndb/__mocks__/content/assets/datopian-logo.png
packages/markdowndb/__mocks__/content/blog/blog1.mdx
packages/markdowndb/__mocks__/content/blog/blog2.mdx
packages/markdowndb/__mocks__/content/blog/blog3.mdx
packages/markdowndb/__mocks__/content/blog0.mdx
packages/markdowndb/__mocks__/content/index.mdx
packages/markdowndb/jest.config.ts
packages/markdowndb/package.json
packages/markdowndb/project.json
packages/markdowndb/src/index.ts
packages/markdowndb/src/lib/markdowndb.spec.ts
packages/markdowndb/src/lib/markdowndb.ts
packages/markdowndb/src/lib/types.ts
packages/markdowndb/tsconfig.json
packages/markdowndb/tsconfig.lib.json
packages/markdowndb/tsconfig.spec.json
pnpm-lock.yaml
tsconfig.base.json

Related to #465 
- created a new package in `packages/markdowndb`
- copied code from `datahub-next/lib/markdowndb`
I've used `@flowershow/markdowndb` name for publishing to npm but this can be changed.

markdowndb package v.1.

---

packages/markdowndb/README.md

Markdowndb README v.1

---

.changeset/moody-schools-relate.md
package-lock.json
package.json

Bump mddb to 0.2.1

---

styles/global.css

Resolves https://github.com/datopian/flowershow/issues/563

🛠️fix: footer position for page with short content
